# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'check.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate, Qt
import pymysql

class Ui_Dialog4(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 640)

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-20, 480, 340, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.rice_result_kg = QtWidgets.QTextEdit(Dialog)
        self.rice_result_kg.setGeometry(QtCore.QRect(50, 170, 280, 200))
        self.rice_result_kg.setObjectName("rice_result_kg")
        ###
        self.rice_pushbutton = QtWidgets.QPushButton(Dialog)
        self.rice_pushbutton.setGeometry(QtCore.QRect(140, 120, 100, 31))
        self.rice_pushbutton.setObjectName("rice_pushbutton")
        self.rice_pushbutton.clicked.connect(self.tem)
     
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def tem(self):
        db = pymysql.connect(host='221.158.6.109', user='root', password='040416', db='qtdata', charset='utf8',
                                     port=3306)
        cursor = db.cursor(pymysql.cursors.DictCursor)
        cursor.execute("SELECT * FROM simulation")
        result = cursor.fetchone()
        print(result)
        self.rice_result_kg.setText("쌀의 적정 온도는 : "+str(result['rice'])+" °C 입니다.")
        self.rice_result_kg.append("바나나의 적정 온도는 : "+str(result['banana'])+" °C 입니다.")
        self.rice_result_kg.append("카사바의 적정 온도는 : "+str(result['casava'])+" °C 입니다.")
        self.rice_result_kg.setFont(QtGui.QFont("Nanum Gothic", 10))
        self.rice_result_kg.setStyleSheet("Color : green")


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.rice_pushbutton.setText(_translate("MainWindow", "적정 온도 출력"))
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog4()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
