# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'erplogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import pymysql
import first
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import uic
from signup import Ui_OtherWindow
from tkinter import *
from tkinter import messagebox
from PyQt5 import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
import json
from collections import OrderedDict

class Ui_MainWindow(object):

    def __init__(self) :
        self.LId = "" # 아이디를 저장할 변수 선언
        self.file_data = OrderedDict() # json 파일 생성을 위한 딕셔너리 생성

    def set_LId(self, id) : # 아이디 설정 함수
        self.LId = id
    
    def get_LId(self) : # 아이디 받아오는 함수
        return self.LId

    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 10, 211, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 56, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(25, 130, 70, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_ID = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_ID.setGeometry(QtCore.QRect(110, 90, 221, 20))
        self.lineEdit_ID.setObjectName("lineEdit_ID")
        self.lineEdit_PW = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PW.setGeometry(QtCore.QRect(110, 130, 221, 20))
        self.lineEdit_PW.setObjectName("lineEdit_PW")
        self.pushButton_LOGIN = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_LOGIN.setGeometry(QtCore.QRect(100, 200, 81, 41))
        self.pushButton_LOGIN.setObjectName("pushButton_LOGIN")
        self.pushButton_SIGNUP = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_SIGNUP.setGeometry(QtCore.QRect(250, 200, 81, 41))
        self.pushButton_SIGNUP.setObjectName("pushButton_SIGNUP")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        self.pushButton_LOGIN.clicked.connect(self.login) # type: ignore
        self.pushButton_SIGNUP.clicked.connect(self.signup) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">ERP 사용자 로그인 </span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "아이디"))
        self.label_3.setText(_translate("MainWindow", "비밀번호"))
        self.pushButton_LOGIN.setText(_translate("MainWindow", "로그인"))
        self.pushButton_SIGNUP.setText(_translate("MainWindow", "회원가입"))

    def login(self):
        text = self.lineEdit_ID.text()
        text1 = self.lineEdit_PW.text()
        db = pymysql.connect(host='127.0.0.1', user='root', password='040416', db='qtdata', charset='utf8',port=3306)
        cursor = db.cursor(pymysql.cursors.DictCursor)

        select_data = [[text, text1]]
        select_sql = "SELECT * FROM `idpw` WHERE id = %s AND pw = %s"
        cursor.executemany(select_sql, select_data)
        result = cursor.fetchone()

        if result is not None:
             messagebox.showinfo('성공', '로그인 성공')
             self.dialog = QtWidgets.QDialog()
             self.ui = first.Ui_Dialog56()
             self.ui.setupUi(self.dialog)
             self.dialog.show()
             MainWindow.hide()
             self.set_LId(result["id"]) # 로그인 성공할 시 result 내부에 id를 self.Lid에 저장
             self.file_data["id"] = self.get_LId() # {"id" : self.Lid} 형태로 저장됨
             with open('id.json', 'w', encoding="utf-8") as make_file :
                json.dump(self.file_data, make_file, indent="\t") # id.json 파일로 저장
             self.LoginId()

        else:
            messagebox.showerror('오류', '로그인 실패')
        db.commit()
        db.close()

    def LoginId(self):
        print(self.get_LId())

    def signup(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_OtherWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        print(self.LId)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    
    
    