# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#가축, 농작물
import erplogin
from PyQt5 import QtCore, QtGui, QtWidgets
from second import Ui_Dialog2
from second_2 import Ui_Dialog2_2


class Ui_Dialog56(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(360, 640)
        self.animal_btn = QtWidgets.QToolButton(Dialog)
        self.animal_btn.setGeometry(QtCore.QRect(70, 130, 220, 80))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(30)
        font.setBold(True)
        self.animal_btn.setFont(font)
        self.animal_btn.setObjectName("animal_btn")
        self.veg_btn = QtWidgets.QToolButton(Dialog)
        self.veg_btn.setGeometry(QtCore.QRect(70, 270, 220, 80))

        ###cancel버튼
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-20, 450, 340, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        ###

        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(30)
        font.setBold(True)
        self.veg_btn.setFont(font)
        self.veg_btn.setObjectName("veg_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        self.animal_btn.clicked.connect(self.click)
        self.veg_btn.clicked.connect(self.click2)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.animal_btn.setText(_translate("Dialog", " 가 축 "))
        self.veg_btn.setText(_translate("Dialog", "농 작 물"))

    def click(self):
        self.Ui_Dialog2 = QtWidgets.QDialog()
        self.ui = Ui_Dialog2()
        self.ui.setupUi(self.Ui_Dialog2)
        self.Ui_Dialog2.show()

    def click2(self):
        self.Ui_Dialog2_2 = QtWidgets.QDialog()
        self.ui = Ui_Dialog2_2()
        self.ui.setupUi(self.Ui_Dialog2_2)
        self.Ui_Dialog2_2.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog56()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

