# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animal_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#농작물 재고 조회, 재고 입력
import erplogin
from PyQt5 import QtCore, QtGui, QtWidgets
from vegetable_im_2 import Ui_MainWindow
from veg_input import MyApp
from check import Ui_Dialog4

class Ui_Dialog2_2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360,640)
        self.toolButton = QtWidgets.QToolButton(Dialog)
        self.toolButton.setGeometry(QtCore.QRect(70, 130, 220, 80))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(25)
        font.setBold(True)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Dialog)
        self.toolButton_2.setGeometry(QtCore.QRect(70, 240, 220, 80))
        self.toolButton_3 = QtWidgets.QToolButton(Dialog)
        self.toolButton_3.setGeometry(QtCore.QRect(70, 350, 220, 80))

        ###cancel버튼
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(-20, 480, 340, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        ###

        #제목 넣기
        self.label = QtWidgets.QLabel(Dialog)
        # 크기 조정
        self.label.setGeometry(QtCore.QRect(95, 40, 180, 60))
        self.label.setObjectName("label")

        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(25)
        font.setBold(True)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName("toolButton_2")
        self.toolButton_3.setFont(font)
        self.toolButton_3.setObjectName("toolButton_3")

        self.retranslateUi(Dialog)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        self.toolButton.clicked.connect(self.click2)
        self.toolButton_2.clicked.connect(self.click)
        self.toolButton_3.clicked.connect(self.click3)


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.toolButton.setText(_translate("Dialog", "재고 조회"))
        self.toolButton_2.setText(_translate("Dialog", "재고 입력"))
        self.toolButton_3.setText(_translate("Dialog", "적정 온도"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" "
                                                "font-size:15pt; font-weight:700;\""
                                                ">&lt; 농 작 물 &gt;</span></p></body></html>"))


    def click(self):
        self.Ui_MainWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.Ui_MainWindow)
        self.Ui_MainWindow.show()

    def click2(self):
        self.MyApp = QtWidgets.QMainWindow()
        self.ui = MyApp()
        # self.ui.setupUi(self.MyApp)
        self.MyApp.show()

    def click3(self):
        self.Ui_Dialog4 = QtWidgets.QDialog()
        self.ui = Ui_Dialog4()
        self.ui.setupUi(self.Ui_Dialog4)
        self.Ui_Dialog4.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog2_2()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
