# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'animal_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#가축 재고 조회, 재고 입력
from PyQt5 import QtCore, QtGui, QtWidgets
from animal_im_2 import Ui_MainWindow2
from animal_input import MyApp

class Ui_Dialog2(object):
    def setupUi(self, Dialog2):
        Dialog2.setObjectName("Dialog2")
        Dialog2.resize(360,640)
        self.toolButton = QtWidgets.QToolButton(Dialog2)
        self.toolButton.setGeometry(QtCore.QRect(70, 130, 220, 80))

        ###cancel버튼
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog2)
        self.buttonBox.setGeometry(QtCore.QRect(-20, 450, 340, 30))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        ###

        #제목 넣기
        self.label = QtWidgets.QLabel(Dialog2)
        #크기 조정
        self.label.setGeometry(QtCore.QRect(120, 40, 140, 60))
        self.label.setObjectName("label")

        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(25)
        font.setBold(True)
        self.toolButton.setFont(font)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(Dialog2)
        self.toolButton_2.setGeometry(QtCore.QRect(70, 270, 220, 80))
        font = QtGui.QFont()
        font.setFamily("Nanum Gothic")
        font.setPointSize(25)
        font.setBold(True)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setObjectName("toolButton_2")

        self.retranslateUi(Dialog2)
        ###
        self.buttonBox.accepted.connect(Dialog2.accept)
        self.buttonBox.rejected.connect(Dialog2.reject)
        ###
        QtCore.QMetaObject.connectSlotsByName(Dialog2)

        self.toolButton_2.clicked.connect(self.click)
        self.toolButton.clicked.connect(self.click2)


    def retranslateUi(self, Dialog2):
        _translate = QtCore.QCoreApplication.translate
        Dialog2.setWindowTitle(_translate("Dialog2", "Dialog2"))
        self.toolButton.setText(_translate("Dialog2", "재고 조회"))
        self.toolButton_2.setText(_translate("Dialog2", "재고 입력"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" "
                                                "font-size:15pt; font-weight:700;\""
                                                ">&lt; 가 축 &gt;</span></p></body></html>"))

    def click(self):
        self.Ui_MainWindow2 = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow2()
        self.ui.setupUi(self.Ui_MainWindow2)
        self.Ui_MainWindow2.show()

    def click2(self):
        self.MyApp = QtWidgets.QMainWindow()
        self.ui = MyApp()
        #self.ui.setupUi(self.MyApp)
        self.MyApp.show()


    # def button1Function(self):
    #     print("btn_1")
    # def button2Function(self):
    #     print("btn_2")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog2 = QtWidgets.QDialog()
    ui = Ui_Dialog2()
    ui.setupUi(Dialog2)
    Dialog2.show()
    sys.exit(app.exec_())
